# site config
title: AdHy Ngurajeka
desc: "Linuxer / Programmer / Thinker"

# jekyll config
sass:
   sass_dir: _sass
   style: compressed
permalink: /:categories/:title.html
exclude: ['Gemfile','Gemfile.lock','Rakefile','.git']
paginate: 4
markdown: kramdown
highlighter: pygments
gems:
   - jekyll-sitemap

# owner stuff
owner:
   name: AdHy Ngurajeka
   realname: Ady Rahmat MA
   nickname: ngurajeka

