# Site wide configuration

title: myBase
description: Base Template for work
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name:
  email:
  twitter:
  google: 
  bio: 
  avatar:  # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "Guardfile", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
#host: 192.168.1.114