# Site settings
title: The Official Ngurajeka Site
email: ngurajeka.92@gmail.com
description: "{ Linuxer / Programmer / Thinker }"
baseurl: ""
url: "http://ngurajeka.com"

sass:
 sass_dir: _sass
 style: compressed
paginate: 5
paginate_path: "blog/page:num/"

owner:
  name: AdHy Ngurajeka
  realname: Ady Rahmat MA
  nickname: ngurajeka
  social_media:
  - name: twitter
    url: http://twitter.com/ngurajeka
  - name: github
    url: http://github.com/ngurajeka
  - name: facebook
    url: http://fb.com/ngurajeka.92
  bio: "a Web Developer"
  avatar: assets/images/me.jpg

# Build settings
markdown: kramdown

#host: 192.168.1.107
